# Generated by Django 2.1.5 on 2019-03-14 16:59

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TicTacToe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('board', django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(default=0), size=3), size=3)),
                ('total_moves', models.IntegerField(default=0)),
                ('player', models.IntegerField(max_length=1)),
                ('winner', models.CharField(default='N', max_length=1)),
            ],
        ),
    ]
