# Generated by Django 2.1.5 on 2019-03-15 17:37

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_auto_20190314_1700'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tictactoe',
            name='board',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(default=0), size=9),
        ),
    ]
