# Generated by Django 2.1.5 on 2019-03-15 18:25

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0004_auto_20190315_1754'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tictactoe',
            name='board',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(default=0), default=[], size=9),
        ),
    ]
