# Generated by Django 2.1.5 on 2019-03-15 18:29

import django.contrib.postgres.fields
from django.db import migrations, models
import game.models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0006_auto_20190315_1828'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tictactoe',
            name='board',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), default=game.models.default_board, size=9),
        ),
    ]
